In [1]:
import os
import sys
import numpy as np

#https://stackoverflow.com/questions/34478398/import-local-function-from-a-module-housed-in-another-directory-with-relative-im/44486700
module_path= os.path.abspath(os.path.join('..',"python"))

if module_path not in sys.path:
    sys.path.append(module_path)

from neural_net import NeuralNetwork

## subsantiating a model

In [2]:
model =NeuralNetwork(3,3,2)

## verifying weights

In [3]:
model.W

array([[-0.03640536,  0.35407066],
       [ 0.08448579,  0.04328669],
       [ 0.12233858,  0.15100866],
       [ 0.35639426,  0.35639426]])

## testing predict function on  known information

**Steps**
1. update weights to known point
2. predict using input
3. test output

In [4]:
w = np.array([[.1,.3,-.2],[-.4,.1,.2],[-.1,-.2,.4],[.2,.2,.2]])
W = np.array([[.5,.2],[-.3,-.3],[.2,.1],[.3,.3]])
inp = np.array([4,8,6])
targ = np.array([.65,.4])

expected output array([0.5729277 , 0.54618944])
expected error 0.0023885891017721714

In [5]:
model.w = w
model.W = W

In [6]:
model.predict(inp)

array([0.5729277 , 0.54618944])

In [7]:
model.predict(inp,targ)

0.0023885891017721714

## testing training methode on known informaiton

using our established weights we would expect one pass of training with an alpha of .2 to be
``` python
array([[ 0.10006569,  0.30081998, -0.1999963 ],  
       [-0.39986862,  0.10163996,  0.2000074 ],  
       [-0.09990147, -0.19877003,  0.40000555],  
       [ 0.20022234,  0.20022234,  0.20022234]])
```  

In [8]:
model.train(inp,targ)
model.w

one pass


array([[ 0.10006569,  0.30081998, -0.1999963 ],
       [-0.39986862,  0.10163996,  0.2000074 ],
       [-0.09990147, -0.19877003,  0.40000555],
       [ 0.20022234,  0.20022234,  0.20022234]])

## testing other activation functions


### hyperbolic tangent

In [9]:
hyberbolic_model = NeuralNetwork(3,3,2,activation='hyperbolic')

In [10]:
print(hyberbolic_model.Actfunc)
print(hyberbolic_model.Der_Actfunc)

<function NeuralNetwork.act_hyperbolic at 0x000001430D39ED30>
<function NeuralNetwork.der_hyperbolic at 0x000001430D39ECA0>


In [17]:
hyberbolic_model.predict(inp)

array([-0.59881694,  0.438502  ])

In [18]:
hyberbolic_model.train(inp,targ)

one pass


### relu

In [11]:
relu_model = NeuralNetwork(3,3,2,activation='relu')
print(relu_model.Actfunc)
print(relu_model.Der_Actfunc)

<function NeuralNetwork.act_relu at 0x000001430D39EAF0>
<function NeuralNetwork.der_relu at 0x000001430D39EA60>


In [12]:
relu_model.predict(inp)

array([0., 0.])

In [13]:
relu_model.train(x=inp,y=targ)

one pass
