In [1]:
import os
import sys
import numpy as np

#https://stackoverflow.com/questions/34478398/import-local-function-from-a-module-housed-in-another-directory-with-relative-im/44486700
module_path= os.path.abspath(os.path.join('..',"python"))

if module_path not in sys.path:
    sys.path.append(module_path)

from neural_net import NeuralNetwork

## subsantiating a model

In [2]:
model =NeuralNetwork(3,3,2)

## verifying weights

In [3]:
model.W

array([[ 0.04060338, -0.02261996],
       [ 0.06383889,  0.34510574],
       [-0.08775385, -0.13498288],
       [ 0.1388488 ,  0.1388488 ]])

## testing predict function on  known information

**Steps**
1. update weights to known point
2. predict using input
3. test output

In [4]:
w = np.array([[.1,.3,-.2],[-.4,.1,.2],[-.1,-.2,.4],[.2,.2,.2]])
W = np.array([[.5,.2],[-.3,-.3],[.2,.1],[.3,.3]])
inp = np.array([4,8,6])
targ = np.array([.65,.4])

expected output array([0.5729277 , 0.54618944])
expected error 0.0023885891017721714

In [5]:
model.w = w
model.W = W

In [6]:
model.predict(inp)

array([0.5729277 , 0.54618944])

In [7]:
model.predict(inp,targ)

0.0023885891017721714

## testing training methode on known informaiton

using our established weights we would expect one pass of training with an alpha of .2 to be
``` python
array([[ 0.10006569,  0.30081998, -0.1999963 ],
       [-0.39986862,  0.10163996,  0.2000074 ],
       [-0.09990147, -0.19877003,  0.40000555],
       [ 0.20022234,  0.20022234,  0.20022234]])
```

In [8]:
model.get_gradients(inp,targ)
model.w

one pass


array([[ 0.10006569,  0.30081998, -0.1999963 ],
       [-0.39986862,  0.10163996,  0.2000074 ],
       [-0.09990147, -0.19877003,  0.40000555],
       [ 0.20022234,  0.20022234,  0.20022234]])

In [9]:
# running training method
model.train(inp,targ)

one pass


## testing on multiple inputs at once

In [10]:
inp_many = np.tile(inp,3).reshape(3,-1)
targ_many = np.tile(targ,3).reshape(3,-1)

In [11]:
for x, y in zip(inp_many, targ_many):
    print(x,y)

[4 8 6] [0.65 0.4 ]
[4 8 6] [0.65 0.4 ]
[4 8 6] [0.65 0.4 ]


In [12]:
for x,y in zip(inp_many,targ_many):
    model.train(x, y)

one pass
one pass
one pass


In [13]:
model.train(inp_many, targ_many)

one pass
one pass
one pass
one epoch
