In [1]:
import os
import sys
import numpy as np
import pprint

#https://stackoverflow.com/questions/34478398/import-local-function-from-a-module-housed-in-another-directory-with-relative-im/44486700
module_path= os.path.abspath(os.path.join('..',"python"))

if module_path not in sys.path:
    sys.path.append(module_path)

from neural_net import NeuralNetwork

## subsantiating a model

In [2]:
model =NeuralNetwork(3,3,2)

## verifying weights

In [3]:
print(model.W)

[[-0.17624824 -0.213211  ]
 [-0.23696381 -0.1695661 ]
 [ 0.46671417  0.18483981]
 [-0.29473947 -0.29473947]]


## testing predict function on  known information

**Steps**
1. update weights to known point
2. predict using input
3. test output

In [4]:
w = np.array([[.1,.3,-.2],[-.4,.1,.2],[-.1,-.2,.4],[.2,.2,.2]])
W = np.array([[.5,.2],[-.3,-.3],[.2,.1],[.3,.3]])
inp = np.array([4,8,6])
targ = np.array([.65,.4])

In [5]:
model.w = w
model.W = W

In [6]:
print(model.predict(inp))

[0.5729277  0.54618944]


expected output:
 array([0.5729277 , 0.54618944])


In [7]:
model.predict(inp,targ)

0.0023885891017721714

expected error
0.0023885891017721714


## testing training methode on known informaiton

using our established weights we would expect one pass of training with an alpha of .2 to be
``` python
array([[ 0.10006569,  0.30081998, -0.1999963 ],  
       [-0.39986862,  0.10163996,  0.2000074 ],  
       [-0.09990147, -0.19877003,  0.40000555],  
       [ 0.20022234,  0.20022234,  0.20022234]])
```  

In [8]:
model.get_gradients(inp,targ)
print(model.w)

one pass
[[ 0.10006569  0.30081998 -0.1999963 ]
 [-0.39986862  0.10163996  0.2000074 ]
 [-0.09990147 -0.19877003  0.40000555]
 [ 0.20022234  0.20022234  0.20022234]]


In [9]:
# running training method
model.train(inp,targ)

one pass


## testing on multiple inputs at once

In [10]:
inp_many = np.tile(inp,3).reshape(3,-1)
targ_many = np.tile(targ,3).reshape(3,-1)

In [11]:
for x, y in zip(inp_many, targ_many):
    print(x,y)

[4 8 6] [0.65 0.4 ]
[4 8 6] [0.65 0.4 ]
[4 8 6] [0.65 0.4 ]


In [12]:
model.w = w
model.W = W
for x,y in zip(inp_many,targ_many):
    model.train(x, y)

print(model.w)

one pass
one pass
one pass
[[ 0.10021268  0.30242286 -0.19995965]
 [-0.39957464  0.10484572  0.2000807 ]
 [-0.09968098 -0.19636571  0.40006053]
 [ 0.20066897  0.20066897  0.20066897]]


In [13]:
model.w = w
model.W = W
model.train(inp_many, targ_many)
print(model.w)

one pass
one pass
one pass
one epoch
[[ 0.10021268  0.30242286 -0.19995965]
 [-0.39957464  0.10484572  0.2000807 ]
 [-0.09968098 -0.19636571  0.40006053]
 [ 0.20066897  0.20066897  0.20066897]]


## testing other activation functions


### hyperbolic tangent

In [14]:
hyberbolic_model = NeuralNetwork(3,3,2,activation='hyperbolic')

In [15]:
print(hyberbolic_model.Actfunc)
print(hyberbolic_model.Der_Actfunc)

<function NeuralNetwork.act_hyperbolic at 0x000001D0E3741670>
<function NeuralNetwork.der_hyperbolic at 0x000001D0E37415E0>


In [16]:
print(hyberbolic_model.predict(inp))

[0.1800521  0.50212848]


In [17]:
hyberbolic_model.train(inp,targ)

one pass


### relu

In [18]:
relu_model = NeuralNetwork(3,3,2,activation='relu')
print(relu_model.Actfunc)
print(relu_model.Der_Actfunc)

<function NeuralNetwork.act_relu at 0x000001D0E3741430>
<function NeuralNetwork.der_relu at 0x000001D0E37413A0>


In [19]:
print(relu_model.predict(inp))

[0.         0.83161399]


In [20]:
relu_model.train(inp,targ)

one pass


## testing batch training

In [21]:
# scaling up input 
inp_many_more = np.tile(inp,11).reshape(-1,3)
targ_many_more = np.tile(targ,11).reshape(-1,2)

In [22]:
print(model.W)
model.train(inp_many_more,targ_many_more,numbatches=4,batchsize=0)
print(model.W)

[[ 0.5004429   0.19916799]
 [-0.29169784 -0.31559512]
 [ 0.21092038  0.07948477]
 [ 0.29008506  0.29008506]]
one batch
one batch
one batch
one batch
[[ 0.50102965  0.19814578]
 [-0.28056113 -0.33499529]
 [ 0.22527011  0.05448392]
 [ 0.2790798   0.2790798 ]]


In [23]:
print(model.w)
model.train(inp_many_more,targ_many_more,batchsize=3)
print(model.w)

[[ 0.10056061  0.30547053 -0.19978581]
 [-0.39887878  0.11094105  0.20042838]
 [-0.09915908 -0.19179421  0.40032128]
 [ 0.20156133  0.20156133  0.20156133]]
one batch
one batch
one batch
one batch
[[ 0.10096551  0.30829845 -0.19950668]
 [-0.39806898  0.11659691  0.20098663]
 [-0.09855174 -0.18755232  0.40073997]
 [ 0.20243932  0.20243932  0.20243932]]


In [24]:
print(relu_model.w)
relu_model.train(inp_many_more,targ_many_more,batchsize=3)
print(relu_model.w)

[[-0.2351093  -0.41444763 -0.36468061]
 [ 0.2591487  -0.74616784 -0.32661409]
 [ 0.06944382 -0.0842686  -0.28649359]
 [-0.5672962  -0.5672962  -0.5672962 ]]
one batch
one batch
one batch
one batch
[[-0.39648679 -0.85653124 -0.24167378]
 [-0.06360627 -1.63033507 -0.08060044]
 [-0.1726224  -0.74739402 -0.10198335]
 [-0.68740977 -0.68740977 -0.68740977]]
