In [1]:
import os
import sys
import numpy as np

#https://stackoverflow.com/questions/34478398/import-local-function-from-a-module-housed-in-another-directory-with-relative-im/44486700
module_path= os.path.abspath(os.path.join('..',"python"))

if module_path not in sys.path:
    sys.path.append(module_path)

from neural_net import NeuralNetwork

## subsantiating a model

In [2]:
model =NeuralNetwork(3,3,2)

## verifying weights

In [3]:
model.W

array([[-0.470476  ,  0.01328629],
       [-0.36249187,  0.38702372],
       [-0.04420145,  0.24850932],
       [-0.46560847, -0.46560847]])

## testing predict function on  known information

**Steps**
1. update weights to known point
2. predict using input
3. test output

In [4]:
w = np.array([[.1,.3,-.2],[-.4,.1,.2],[-.1,-.2,.4],[.2,.2,.2]])
W = np.array([[.5,.2],[-.3,-.3],[.2,.1],[.3,.3]])
inp = np.array([4,8,6])
targ = np.array([.65,.4])

expected output array([0.5729277 , 0.54618944])
expected error 0.0023885891017721714

In [5]:
model.w = w
model.W = W

In [6]:
model.predict(inp)

array([0.5729277 , 0.54618944])

In [7]:
model.predict(inp,targ)

0.0023885891017721714

## testing training methode on known informaiton

using our established weights we would expect one pass of training with an alpha of .2 to be
``` python
array([[ 0.10006569,  0.30081998, -0.1999963 ],  
       [-0.39986862,  0.10163996,  0.2000074 ],  
       [-0.09990147, -0.19877003,  0.40000555],  
       [ 0.20022234,  0.20022234,  0.20022234]])
```  

In [8]:
model.get_gradients(inp,targ)
model.w

one pass


array([[ 0.10006569,  0.30081998, -0.1999963 ],
       [-0.39986862,  0.10163996,  0.2000074 ],
       [-0.09990147, -0.19877003,  0.40000555],
       [ 0.20022234,  0.20022234,  0.20022234]])

In [9]:
# running training method
model.train(inp,targ)

one pass


## testing on multiple inputs at once

In [10]:
inp_many = np.tile(inp,3).reshape(3,-1)
targ_many = np.tile(targ,3).reshape(3,-1)

In [11]:
for x, y in zip(inp_many, targ_many):
    print(x,y)

[4 8 6] [0.65 0.4 ]
[4 8 6] [0.65 0.4 ]
[4 8 6] [0.65 0.4 ]


In [12]:
for x,y in zip(inp_many,targ_many):
    model.train(x, y)

one pass
one pass
one pass


In [13]:
model.train(inp_many, targ_many)

one pass
one pass
one pass
one epoch


## testing other activation functions


### hyperbolic tangent

In [14]:
hyberbolic_model = NeuralNetwork(3,3,2,activation='hyperbolic')

In [15]:
print(hyberbolic_model.Actfunc)
print(hyberbolic_model.Der_Actfunc)

<function NeuralNetwork.act_hyperbolic at 0x0000025FDB09FB80>
<function NeuralNetwork.der_hyperbolic at 0x0000025FDB09FAF0>


In [16]:
hyberbolic_model.predict(inp)

array([ 0.24970897, -0.11919236])

In [17]:
hyberbolic_model.train(inp,targ)

one pass


### relu

In [18]:
relu_model = NeuralNetwork(3,3,2,activation='relu')
print(relu_model.Actfunc)
print(relu_model.Der_Actfunc)

<function NeuralNetwork.act_relu at 0x0000025FDB09F940>
<function NeuralNetwork.der_relu at 0x0000025FDB09F8B0>


In [19]:
relu_model.predict(inp)

array([0., 0.])

In [22]:
relu_model.train(inp,targ)

one pass


## testing batch training

In [28]:
# scaling up input 
inp_many_more = np.tile(inp,11).reshape(-1,3)
targ_many_more = np.tile(targ,11).reshape(-1,2)

In [33]:
print(model.W)
model.train(inp_many_more,targ_many_more,numbatches=4,batchsize=0)
print(model.W)

[[ 0.50375217  0.19424675]
 [-0.22811278 -0.41009538]
 [ 0.2895082  -0.03766354]
 [ 0.25026437  0.25026437]]
one batch
one batch
one batch
one batch
[[ 0.50423538  0.19365861]
 [-0.21884342 -0.42137775]
 [ 0.30043806 -0.05096741]
 [ 0.24781667  0.24781667]]


In [34]:
print(model.w)
model.train(inp_many_more,targ_many_more,batchsize=3)
print(model.w)

[[ 0.1033657   0.31935062 -0.19740627]
 [-0.3932686   0.13870124  0.20518745]
 [-0.09495145 -0.17097407  0.40389059]
 [ 0.20632751  0.20632751  0.20632751]]
one batch
one batch
one batch
one batch
[[ 0.10385439  0.32103351 -0.19695668]
 [-0.39229122  0.14206701  0.20608664]
 [-0.09421842 -0.16844974  0.40456498]
 [ 0.2069828   0.2069828   0.2069828 ]]
